# GitHub "Sponsor this project" button + funding links.
# Docs: https://docs.github.com/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository
github: [johndellarciprete]
custom:
  - 'https://www.paypal.com/ncp/payment/G2KL8VSBQJUYA'
  - 'https://venmo.com/John-DellArciprete?txn=pay&amount=10'
